
# run 'sudo apt install libpq-dev'

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('RAILS_DATABASE_USER') { 'vagrant' } %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD') { 'vagrant' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: 5432
  timeout: 5000

development:
  <<: *default
  database: organization_development

test:
  <<: *default
  database: organization_test

production:
  <<: *default
  database: organization_production
