#!/usr/bin/env ruby

if ARGV.size > 0
  if ARGV[0].eql? '-T'
    system "rake -T"
    return
  elsif ARGV[0].include? ':'
    require 'rake'
    Rake.load_rakefile 'Rakefile' if File.exists? 'Rakefile'
    Rake::Task[ARGV.shift].invoke(ARGV)
    return
  end
end

require 'pry'

require 'bundler/setup'
require 'ros'

Ros::Cli.start
