#!/usr/bin/env ruby

if ARGV[0]&.eql? '-T'
  res = %x(rake -T #{ARGV[1]})
  STDOUT.puts res.gsub(/^rake/, 'ros').gsub("\nrake", "\nros")
elsif ARGV[0]&.include? ':'
  require 'rake'
  Rake.load_rakefile 'Rakefile' if File.exists? 'Rakefile'
  Rake::Task[ARGV.shift].invoke(ARGV)
else
  require 'bundler/setup'
  require 'ros'
  require 'ros/cli'
  Ros::Cli.start
end
