require:
  - rubocop-rails
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - '**/db/seeds/**/*.rb'
    - '**/spec/models/**/*.rb'
    - '**/spec/policies/**/*.rb'
    - '**/spec/requests/**/*.rb'
AllCops:
  Exclude:
    - '**/schema.rb'
    - '**/db/migrate/*.rb'
    - '**/db/seeds.rb'
    - '**/*.gemspec'
    - '**/bin/*'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Gemfile'
    - 'services/storage/sqs_test.rb'
