---
components:
  be:
    config:
      feature_set: stage
      feature_from_branch: no
    environment:
      nginx_host_port: 3001
    components:
      application:
        components:
          services:
            components:
              kafkastack:
                config:
                  enabled: no
              fluentd:
                config:
                  enabled: no
              sftp:
                config:
                  enabled: no
          platform:
            components:
              # account:
              #   mount: no
              # billing:
              #   mount: no
              cognito:
                config:
                  mount: no
              comm:
                config:
                  mount: no
              iam:
                config:
                  mount: no
              organization:
                config:
                  mount: no
              storage:
                config:
                  enabled: no
                  mount: no
