# Values defined here override any values defined in deployment.yml
---
components:
  be:
    environment:
      nginx_host_port: 3000
    components:
      infra:
        config:
          cluster:
            type: instance
        components:
          vpc:
          instance:
            config:
              provider: aws
      application:
        config:
          feature_set: test
          feature_from_branch: no
          feature_from_tag: no
        environment:
          bucket_endpoint_url: http://localstack:4572
          aws_access_key_id: this_key_from_development_yml
          aws_secret_access_key: this_key_from_development_yml
          aws_default_region: localstack
        components:
          services:
            components:
              fluentd:
                config:
                  enabled: no
              localstack:
              postgres:
              redis:
              wait:

          platform:
            environment:
              redis_url: redis://redis:6379
              platform:
                request_logging:
                  enabled: no
                event_logging:
                  enabled: no
                infra:
                  resources:
                    storage:
                      config: &infra_services_object_storage
                        endpoint: http://localstack:4572
                        force_path_style: yes
                        # region: ap-southeast-1
                      buckets:
                        app:
                          <<: *infra_services_object_storage
                        cdn:
                          <<: *infra_services_object_storage
            components:
              # account:
              #   config:
              #     mount: no
              #     profiles: ['server']
              # billing:
              #   config:
              #     mount: no
              #     profiles: ['server']
              cognito:
                config:
                  mount: no
                  profiles: ['server']
              comm:
                config:
                  mount: no
                  profiles: ['server']
              iam:
                config:
                  mount: no
                  profiles: ['server']
              organization:
                config:
                  mount: no
                  profiles: ['server']
              storage:
                config:
                  mount: no
                  profiles: ['server']
                environment:
                  platform:
                    infra:
                      resources:
                        mq:
                          queues:
                            storage_data:
                              endpoint: http://localstack:4576
                              verify_checksums: no
                              # region: ap-southeast-1
                              provider: aws
                              bucket_name: app-development-demo-cnfs-io
