# Configuration values defined here override any values defined in development.yml
---
components:
  be:
    components:
      infra:
        config:
          cluster:
            type: kubernetes
        components:
          vpc:
            config:
              provider: aws
          kubernetes:
            config:
              provider: aws
              name: develop
      application:
        config:
          dns:
            root_domain: perxtech.org
            sub_domain: ros-test
        components:
          services:
            components:
              ingress:
              kafka:
              kafka-zookeeper:
              kafka-schema-registry:
              kafka-connect:
              postgres:
              redis:
          platform:
            config:
              images:
                rails:
                  # NOTE: for production set rails_env to production
                  build_args:
                    rails_env: development
            components:
              cognito:
                config:
                  profiles: ['server']
              comm:
                config:
                  profiles: ['server']
              organization:
                config:
                  profiles: ['server']
              iam:
                config:
                  profiles: ['server']
              storage:
                config:
                  profiles: ['server']
