# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'awesome_print'
gem 'pg'
gem 'pry-rails'

gem 'ros-core', path: '../core'
gem 'ros_sdk', path: '../sdk'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rails-erd'
end


group :development, :test do
  gem 'brakeman', require: false
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'spring-commands-rspec'
end
