version: 2.1
executors:
  ros-cli:
    docker:
      - image: railsonservices/cli
        entrypoint: /bin/bash -l
commands:
  docker_login:
    description: Login to dockerhub
    steps:
      - run:
          name: Login to dockerhub
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin
jobs:
  build_and_test:
    working_directory: ~/project
    executor: ros-cli
    shell: /bin/bash --login -eo pipefail
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - checkout
      - docker_login
      - run:
          command: ros be infra init -l
          environment:
            ROS_ENV: test
      - run:
          name: Generate the platform environment
          command: ros be init
      - run:
          name: Build Docker Images 
          command: ros be build
      - run:
          name: Push Docker Images
          command: ros be push
      # TODO
      # - run:
      #     name: Run Tests
      #     command: ros be test
      #     environment:
      #       ROS_PROFILE: image
workflows:
  build_and_test:
    jobs:
      - build_and_test
