# frozen_string_literal: true

source ENV['GEM_SERVER'] || 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'pry-rails'
gem 'awesome_print'
gem 'pg'

gem 'ros-core', path: '../../lib/core'
gem 'ros_sdk', path: '../../lib/sdk'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rails-erd'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'airborne'
  gem 'brakeman', require: false
  gem 'dotenv'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'jsonapi-resources-matchers'
  gem 'pry-stack_explorer'
  gem 'pundit-matchers'
  gem 'rspec-rails'
  gem 'perx-rubocop', '~> 0.0.1.rc1'
  gem 'shoulda-matchers'
  gem 'spring-commands-rspec'
  gem 'rspec_junit_formatter'
end

group :production do
  gem 'puma'
end
