
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rake'
git 'https://github.com/rails-on-services/ros.git', glob: '**/*.gemspec', branch: :master do
  gem 'ros', path: 'ros/ros'
  gem 'ros-cognito', path: 'ros/cognito'
  gem 'ros-comm', path: 'ros/comm'
  gem 'ros-iam', path: 'ros/iam'
end
