---
localstack: &localstack
  service: s3
  bucket: test
  access_key_id: hello
  secret_access_key: hello
  endpoint: http://localstack:4572
  region: localstack
  force_path_style: true

amazon_app: &amazon_app
  service: s3
  bucket: <%= ENV['PLATFORM__INFRA__RESOURCES__STORAGE__BUCKETS__APP__NAME'] %>
  # access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  # secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>

amazon_cdn: &amazon_cdn
  service: s3
  bucket: <%= ENV['PLATFORM__INFRA__RESOURCES__STORAGE__BUCKETS__CDN__NAME'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>

disk: &disk
  service: Disk
  root: <%= Rails.root.join('tmp', 'active_storage') %>

development:
  # <<: *localstack
  # <<: *disk
  <<: *amazon_app

test:
  # <<: *disk
  <<: *localstack
