local:
  service: s3
  bucket: home
  access_key_id: hello
  secret_access_key: hello
  endpoint: http://localstack:4572
  region: 'ap-southeast-1'
  force_path_style: true

test:
  service: Disk
  root: <%= Rails.root.join("tmp","storage") %>