---
localstack: &localstack
  service: s3
  bucket: test
  access_key_id: hello
  secret_access_key: hello
  endpoint: http://localstack:4572
  region: localstack
  force_path_style: true

amazon: &amazon
  service: s3
  bucket: <%= ENV['PLATFORM__INFRA__RESOURCES__MQ__QUEUES__STORAGE_DATA__BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>

disk: &disk
  service: Disk
  root: <%= Rails.root.join('tmp', 'active_storage') %>

development:
  # <<: *localstack
  # <<: *disk
  <<: *amazon

test:
  <<: *disk
