---
localstack:
  service: s3
  bucket: home
  access_key_id: hello
  secret_access_key: hello
  endpoint: http://localstack:4572
  region: 'ap-southeast-1'
  force_path_style: true

amazon:
  service: s3
  bucket: test
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: 'ap-southeast-1'

test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'test', 'active_storage') %>
