# frozen_string_literal: true

# Include common Gemfile
%w[../Gemfile].each do |gemfile|
  instance_eval(File.read(Pathname.new(File.dirname(__FILE__)).join(gemfile)))
end

# Include any gems specific to this service
gemspec

gem 'aasm'
gem 'trailblazer-activity'
gem 'trailblazer-activity-dsl-linear'
