source ENV['GEM_SERVER'] || 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'pg'
gem 'pry-rails'
gem 'awesome_print'
gem 'dotenv'

gem 'ros_sdk', path: '../sdk'
group :development, :test do
  gem 'brakeman', require: false
  gem 'spring-commands-rspec'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
end
