source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'pg'
gem 'pry-rails'
gem 'awesome_print'
gem 'ros_sdk', path: '../sdk'
group :development, :test do
  gem 'brakeman', require: false
  gem 'pry-byebug'
  gem 'spring-commands-rspec'
  gem 'database_cleaner'
end
