# SQLite version 3.x
#   gem install sqlite3
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('RAILS_DATABASE_USER') { 'admin' } %>
  password: <%= ENV.fetch('RAILS_DATABASE_PASSWORD') { 'admin' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: iam_development
  gssencmode: disable

test:
  <<: *default
  database: iam_test
  gssencmode: disable
  # database: db/test.sqlite3
  # database: ':memory:'

production:
  <<: *default
  database: iam_production
